/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RampRouteImport } from './routes/ramp'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EarnAddLiquidityRouteImport } from './routes/earn/add-liquidity'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/transfer.lazy').then((d) => d.Route))
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/security.lazy').then((d) => d.Route))
const RampRoute = RampRouteImport.update({
  id: '/ramp',
  path: '/ramp',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/ramp.lazy').then((d) => d.Route))
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/earn.lazy').then((d) => d.Route))
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/app.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const EarnAddLiquidityRoute = EarnAddLiquidityRouteImport.update({
  id: '/add-liquidity',
  path: '/add-liquidity',
  getParentRoute: () => EarnRoute,
} as any).lazy(() =>
  import('./routes/earn/add-liquidity.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/earn': typeof EarnRouteWithChildren
  '/history': typeof HistoryRoute
  '/ramp': typeof RampRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfer': typeof TransferRoute
  '/earn/add-liquidity': typeof EarnAddLiquidityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/earn': typeof EarnRouteWithChildren
  '/history': typeof HistoryRoute
  '/ramp': typeof RampRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfer': typeof TransferRoute
  '/earn/add-liquidity': typeof EarnAddLiquidityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/earn': typeof EarnRouteWithChildren
  '/history': typeof HistoryRoute
  '/ramp': typeof RampRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/transfer': typeof TransferRoute
  '/earn/add-liquidity': typeof EarnAddLiquidityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/earn'
    | '/history'
    | '/ramp'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/transfer'
    | '/earn/add-liquidity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/earn'
    | '/history'
    | '/ramp'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/transfer'
    | '/earn/add-liquidity'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/earn'
    | '/history'
    | '/ramp'
    | '/security'
    | '/settings'
    | '/sitemap.xml'
    | '/transfer'
    | '/earn/add-liquidity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  EarnRoute: typeof EarnRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  RampRoute: typeof RampRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramp': {
      id: '/ramp'
      path: '/ramp'
      fullPath: '/ramp'
      preLoaderRoute: typeof RampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn/add-liquidity': {
      id: '/earn/add-liquidity'
      path: '/add-liquidity'
      fullPath: '/earn/add-liquidity'
      preLoaderRoute: typeof EarnAddLiquidityRouteImport
      parentRoute: typeof EarnRoute
    }
  }
}

interface EarnRouteChildren {
  EarnAddLiquidityRoute: typeof EarnAddLiquidityRoute
}

const EarnRouteChildren: EarnRouteChildren = {
  EarnAddLiquidityRoute: EarnAddLiquidityRoute,
}

const EarnRouteWithChildren = EarnRoute._addFileChildren(EarnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  EarnRoute: EarnRouteWithChildren,
  HistoryRoute: HistoryRoute,
  RampRoute: RampRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
